name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: show github context -- for testing purposes
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: SSH into VM and fetch latest source code
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{secrets.KEY}}
          username: ${{secrets.USERNAME}}
          host: ${{secrets.HOST}}
          script: |
            cd fso-part_11_ex11.20
            git stash
            git pull
            git stash pop
      - name: SSH into VM and run deployment script
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{secrets.KEY}}
          username: ${{secrets.USERNAME}}
          host: ${{secrets.HOST}}
          script: |
            cd fso-part_11_ex11.20
            chmod +x deploy.sh
            ./deploy.sh
      # - name: test success
      #   uses: rjstone/discord-webhook-notify@v1
      #   if: success()
      #   with:
      #     severity: info
      #     text: A new version of the blog app deployed
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      # - name: test failture
      #   uses: rjstone/discord-webhook-notify@v1
      #   if: failure()
      #   with:
      #     severity: error
      #     text: Build failed
      #     description: commit ${{ github.event.commits[0].url }} by ${{ github.event.commits[0].author.name }} broke the build :(
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  # tag_release:
  #   needs: [simple_deployment_pipeline]
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Bump version and push tag
  #       if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
  #       uses: anothrNick/github-tag-action@1.67.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         DEFAULT_BUMP: patch
  #         WITH_V: true
